services:

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    networks:
      - app_network
    volumes:
      - ../files/capacitor_ota/docker-app-data/mysql_data:/var/lib/mysql

  api:
    build:
      context: .
      dockerfile: Dockerfile.prod
    env_file:
      - .env
    networks:
      - app_network
    depends_on:
      - mysql

networks:
  app_network:
    driver: bridge